export const ALL_PRODUCTS = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    price: 199.99,
    category: "Electronics",
    rating: 4.8,
    image: "/wireless-headphones.png",
  },
  {
    id: 2,
    name: "Luxury Watch Collection",
    price: 349.99,
    category: "Accessories",
    rating: 4.9,
    image: "/luxury-watch.jpg",
  },
  {
    id: 3,
    name: "Designer Sunglasses",
    price: 129.99,
    category: "Fashion",
    rating: 4.7,
    image: "/designer-sunglasses.png",
  },
  {
    id: 4,
    name: "Premium Camera",
    price: 599.99,
    category: "Electronics",
    rating: 4.9,
    image: "/professional-camera.png",
  },
  {
    id: 5,
    name: "Leather Backpack",
    price: 89.99,
    category: "Fashion",
    rating: 4.6,
    image: "/brown-leather-backpack.png",
  },
  {
    id: 6,
    name: "Smart Watch Pro",
    price: 249.99,
    category: "Electronics",
    rating: 4.8,
    image: "/modern-smartwatch.png",
  },
  {
    id: 7,
    name: "Vintage Camera Bag",
    price: 74.99,
    category: "Accessories",
    rating: 4.5,
    image: "/camera-bag.jpg",
  },
  {
    id: 8,
    name: "Gold Ring Collection",
    price: 299.99,
    category: "Accessories",
    rating: 4.9,
    image: "/gold-ring.png",
  },
  {
    id: 9,
    name: "Canvas Sneakers",
    price: 64.99,
    category: "Fashion",
    rating: 4.4,
    image: "/canvas-sneakers.png",
  },
  {
    id: 10,
    name: "Portable Charger",
    price: 39.99,
    category: "Electronics",
    rating: 4.7,
    image: "/portable-charger-lifestyle.png",
  },
  { id: 11, name: "Silk Scarf", price: 44.99, category: "Fashion", rating: 4.3, image: "/flowing-silk-scarf.png" },
  {
    id: 12,
    name: "Wireless Earbuds",
    price: 129.99,
    category: "Electronics",
    rating: 4.6,
    image: "/wireless-earbuds.png",
  },
  {
    id: 13,
    name: "iPhone 15 Pro Max",
    price: 1199.99,
    category: "Electronics",
    rating: 4.9,
    image: "/iphone-15-pro.jpg",
  },
  {
    id: 14,
    name: "Samsung Galaxy S24 Ultra",
    price: 1099.99,
    category: "Electronics",
    rating: 4.8,
    image: "/samsung-galaxy-s24.jpg",
  },
  {
    id: 15,
    name: "Google Pixel 8 Pro",
    price: 899.99,
    category: "Electronics",
    rating: 4.7,
    image: "/google-pixel-8.jpg",
  },
  {
    id: 16,
    name: "OnePlus 12",
    price: 749.99,
    category: "Electronics",
    rating: 4.6,
    image: "/oneplus-12.jpg",
  },
  {
    id: 17,
    name: "Xiaomi 14 Ultra",
    price: 699.99,
    category: "Electronics",
    rating: 4.5,
    image: "/xiaomi-14-ultra.jpg",
  },
  {
    id: 18,
    name: "Nothing Phone 2",
    price: 599.99,
    category: "Electronics",
    rating: 4.4,
    image: "/nothing-phone-2.jpg",
  },
]
